# Generated by Django 6.0.4 on 2026-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnutricionista',
            name='rol',
            field=models.CharField(choices=[('nutricionista', 'Nutricionista'), ('admin_plataforma', 'Administrador de Plataforma')], default='nutricionista', max_length=30, verbose_name='Rol en la plataforma'),
        ),
    ]
