# Generated by Django 6.0.5 on 2026-05-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Ej: Diabetes tipo 2, hipertensión, hipotiroidismo', verbose_name='Condiciones médicas')),
                ('alergias', models.TextField(blank=True, help_text='Ej: Maní, lácteos, gluten, mariscos', verbose_name='Alergias')),
                ('notas_generales', models.TextField(blank=True, help_text='Observaciones adicionales relevantes para el nutricionista', verbose_name='Notas generales')),
                ('estado', models.BooleanField(default=True, help_text='Desmarcar para inactivar al paciente sin borrar sus datos', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['nombre', 'apellido'], name='pacientes_p_nombre_3e711c_idx'), models.Index(fields=['telefono'], name='pacientes_p_telefon_f5fa8f_idx')],
            },
        ),
    ]
