# Generated by Django 6.0.5 on 2026-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso inicial o de referencia del paciente', max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
