# Generated by Django 6.0.5 on 2026-05-22 16:14

import pacientes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_fecha_nacimiento_alter_paciente_peso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(default='00000000', max_length=8, validators=[pacientes.validators.validate_dni], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[pacientes.validators.validate_nombre_apellido], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(validators=[pacientes.validators.validate_fecha_nacimiento_edad], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[pacientes.validators.validate_nombre_apellido], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso inicial o de referencia del paciente', max_digits=5, validators=[pacientes.validators.validate_peso], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[pacientes.validators.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('nutricionista', 'dni')},
        ),
    ]
