# Generated by Django 6.0.5 on 2026-05-22 16:32

import pacientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_dni_alter_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, validators=[pacientes.validators.validate_dni], verbose_name='DNI'),
        ),
    ]
