# Generated by Django 6.0.7 on 2026-07-11 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_archivopaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Acceso Móvil'),
        ),
        migrations.CreateModel(
            name='CodigoVinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Vinculación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('expira_en', models.DateTimeField(verbose_name='Expira en')),
                ('utilizado', models.BooleanField(default=False, verbose_name='Utilizado')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_vinculacion', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Código de Vinculación',
                'verbose_name_plural': 'Códigos de Vinculación',
            },
        ),
    ]
