# Generated by Django 6.0.7 on 2026-07-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_consulta_archivopaciente_consulta_and_more'),
        ('pacientes', '0015_paciente_usuario_codigovinculacion'),
    ]

    operations = [
    ]
