# Generated by Django 6.0.7 on 2026-07-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_merge_20260711_2109'),
        ('pacientes', '0017_merge_20260711_2227'),
    ]

    operations = [
    ]
