# Generated by Django 6.0.7 on 2026-07-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_cita_table'),
        ('pacientes', '0018_merge_20260712_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='agendas.cita', verbose_name='Cita originaria'),
        ),
    ]
