# Generated by Django 6.0.7 on 2026-07-13 09:26

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0019_alter_consulta_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopaciente',
            name='archivo',
            field=models.FileField(upload_to=pacientes.models.ruta_archivo_paciente, verbose_name='Archivo'),
        ),
    ]
