# Generated by Django 6.0.7 on 2026-07-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_cita_table'),
        ('facturacion', '0006_plan_gratis_7_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='agendas.cita', verbose_name='Cita asociada'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='metodo_pago_usado',
            field=models.CharField(blank=True, choices=[('stripe', 'Tarjeta (Stripe)'), ('yape', 'Yape'), ('plin', 'Plin'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de pago utilizado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Tarjeta (Stripe)'), ('yape', 'Yape'), ('plin', 'Plin'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
