# Generated by Django 6.0.5 on 2026-05-21 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, verbose_name='Nombre del alimento')),
                ('categoria', models.CharField(choices=[('cereales', 'Cereales y granos'), ('lacteos', 'Lácteos'), ('carnes', 'Carnes y aves'), ('pescados', 'Pescados y mariscos'), ('huevos', 'Huevos'), ('legumbres', 'Legumbres'), ('verduras', 'Verduras y hortalizas'), ('frutas', 'Frutas'), ('grasas', 'Grasas y aceites'), ('bebidas', 'Bebidas'), ('snacks', 'Snacks y aperitivos'), ('otros', 'Otros')], db_index=True, default='otros', max_length=20, verbose_name='Categoría')),
                ('calorias_100g', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calorías (kcal/100g)')),
                ('proteinas_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteínas (g/100g)')),
                ('carbohidratos_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbohidratos (g/100g)')),
                ('grasas_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grasas (g/100g)')),
                ('fibra_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fibra (g/100g)')),
                ('porcion_referencia', models.CharField(blank=True, help_text='Ej: 1 taza (240ml), 1 unidad mediana (150g)', max_length=100, verbose_name='Porción de referencia')),
                ('estado', models.BooleanField(default=True, help_text='Desmarcar para dar de baja el alimento del catálogo', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre', 'categoria'], name='nutricion_a_nombre_f4cc38_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Plan de pérdida de peso - Enero 2025', max_length=200, verbose_name='Nombre del plan')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco si el plan no tiene fecha de término definida', null=True, verbose_name='Fecha de fin')),
                ('objetivo', models.CharField(choices=[('perdida_peso', 'Pérdida de peso'), ('ganancia_muscular', 'Ganancia muscular'), ('mantenimiento', 'Mantenimiento'), ('salud_general', 'Salud general')], max_length=30, verbose_name='Objetivo')),
                ('calorias_diarias', models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(500)], verbose_name='Calorías diarias (kcal)')),
                ('proteinas_g', models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteínas diarias (g)')),
                ('carbohidratos_g', models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbohidratos diarios (g)')),
                ('grasas_g', models.DecimalField(decimal_places=1, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grasas diarias (g)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=True, help_text='Solo puede haber un plan activo por paciente', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComidaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], db_index=True, max_length=10, verbose_name='Día de la semana')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=10, verbose_name='Tipo de comida')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción libre de la comida para el paciente', verbose_name='Descripción')),
                ('calorias_estimadas', models.PositiveIntegerField(default=0, verbose_name='Calorías estimadas (kcal)')),
                ('alimentos_sugeridos', models.ManyToManyField(blank=True, related_name='comidas_plan', to='nutricion.alimento', verbose_name='Alimentos sugeridos')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='nutricion.plannutricional', verbose_name='Plan nutricional')),
            ],
            options={
                'verbose_name': 'Comida del plan',
                'verbose_name_plural': 'Comidas del plan',
                'ordering': ['dia_semana', 'tipo_comida'],
            },
        ),
        migrations.AddIndex(
            model_name='plannutricional',
            index=models.Index(fields=['paciente', 'estado'], name='nutricion_p_pacient_fef806_idx'),
        ),
        migrations.AddIndex(
            model_name='plannutricional',
            index=models.Index(fields=['fecha_inicio'], name='nutricion_p_fecha_i_63defb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comidaplan',
            unique_together={('plan', 'dia_semana', 'tipo_comida')},
        ),
    ]
