# Generated by Django 6.0.7 on 2026-07-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_entregable_consulta_medidacorporal_consulta_and_more'),
        ('seguimiento', '0005_remove_notaclinica_contenido'),
    ]

    operations = [
    ]
