# Generated by Django 6.0.7 on 2026-07-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_merge_20260711_1027'),
        ('seguimiento', '0006_merge_20260711_1601'),
    ]

    operations = [
    ]
