# Generated by Django 6.0.7 on 2026-07-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_cita_table'),
        ('seguimiento', '0007_merge_20260711_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='agendas.cita', verbose_name='Consulta / Cita'),
        ),
        migrations.AlterField(
            model_name='notaclinica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='agendas.cita', verbose_name='Cita relacionada'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones', to='agendas.cita', verbose_name='Consulta / Cita'),
        ),
    ]
